services:
  postgres:
    image: postgres:15-alpine
    container_name: boutique_db
    environment:
      POSTGRES_DB:
      POSGRES_PASSWORD:
      POSGRES_USER:
      POSTGRES_MULTYBITE:
    ports:
      - "5432:5432" 

    volumes:
      - postgres_data:var/lib/postgresql/data 
      - ./database/init:docker-entrypoint.initdb.d

    networks:
      - boutique-networks

    healtcheck:
    test: ["CMD-SHELL", pg_isready, -U posgres"]
    intervals: 30s
    timeout: 10s
    retries: 5s 

    depends_on: 
      database:
        condition: service_healthy


  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-dev
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - boutique-networks
    restart: unless-stopped

  grafana:
    image:
    container_name: grafana-dev
    ports:
      - "3007:3000"
    env:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin-123
      GF_ALLOW_USER_SIGN_UP: false

    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - boutique-networks
    restart: unless-stopped

  gateway:
    build:
      context: ./backend/services/auth
      dockerfile: Dockerfile
    container_name: gateway
    ports:
      - "3001:3001"
    environment:
     - NODE_ENV=development
     - PORT=3001
     - AUTH_SERVICE_URL=http://auth:3002
     - PRODUCT_SERVICE_URL=http://product:3003
     - ORDER_SERVICE_URL=http://order-service:3004
     - ORDERS_SERVICE_URL=http://orders:3005
     - USER_SERVICE_URL=http://service:3006
    depends_on:
      postgres:
        condition: service_healthy   
    networks:
      - boutique-networks
    restart: unless-stopped

  auth:
    build: 
      context: ./backend/services/auth
      dockerfile: Dockerfile
    container_name: auth
    ports:
      - "3002:3002"
    env:
     - ENV_NAME=development 
     - PORT=3002
     - DATABASE_URL=postgresql://postgres:posgres123@posgres:5432/auth
    depends_on:
      condition: service_healthy
    networks:
      - boutique_network
    restart: unless_stopped

  product:
    build:
      context: ./backend/services/product-service
      dockerfile: Dockerfile
    container_name: product
    ports:
      - "3003:3003"
    environment:
      - ENV_NODE=development
      - PORT=3003
      - DATABASE_URL=postgresql://postgres:postgres123@posgres:5432/product
    depends_on:
      - condition: service_healthy
    networks:
      - boutique_network
    restart: unless_stopped

  order_service:
    build:
      context: ./backend/services/order-service
      dockerfile: Dockerfile
    container_name: order-service
    ports:
      - "3004:3004"
    environment:
      - ENV_NODE=development
      - PORT=3004
      - DATABASE_URL=posgres://posgres:posgres123@posgres:5432/order_service
    depends_on:
      condition: service_healthy
    networks:
      - boutique_network
    restart: unless_stopped
    
  orders: 
    build:
      context: ./backend/services/orders/
      dockerfile: Dockerfile
    container_name: orders
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=development
      - PORT=3005
      - DATABASE_URL=posgres://postgres:posgres123@posgres:5432/orders
    depends_on:
      condition: service_healthy
    networks:
      - boutique_network
    restart: unless_stopped

  user:
    build:
      context: ./backend/services/user-service
      dockerfile: Dockerfile
    container_name: user
    ports:
      - "3006:3006"

  frontend:
    build: 
      context: ./projects/boutique-microservices/frontend/
      dockerfile: Dockerfile

volumes:
  postgres_data:
    driver: local

  prometheus_data:
    driver: local

  grafana_data:
    driver: local

  networks:
    boutique_network:
      driver: bridge