apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: dev
  labels:
    app.kubernetes.io/part-of: dev
    app.kubernetes.io/component: frontend
    app.kubernetes.io/name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: frontendd
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: dev
        app.kubernetes.io/component: frontend
        app.kubernetes.io/name: frontend 
    spec:
      automountServiceAccountToken: false
      tolerations:
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 300
      containers:
        - name: frontend 
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
              protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false  # Postgres needs write access
            runAsNonRoot: false  # Postgres image runs as root by default

---

apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app.kubernetes.io/name: frontendd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
