apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: dev
  labels:
    app.kubernetes.io/part-of: dev
    app.kubernetes.io/component: database
    app.kubernetes.io/name: db-postgres
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 8Gi
