apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: dev
  labels:
    app.kubernetes.io/part-of: dev
type: Opaque
data:
  POSTGRES_USER: eW9nYXdzZXRpYXdhbjM0MjM0
  POSTGRES_PASSWORD: YWluZy1tYWNhbi1rdW1iYW5nMDkwMDk5MDk5OTA5
  POSTGRES_DB: ZGItZGVtbw==