apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-postgres
  namespace: dev
  labels:
    app.kubernetes.io/part-of: dev
    app.kubernetes.io/component: database
    app.kubernetes.io/name: db-postgres
spec:
  serviceName: database
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: db-postgres
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: dev
        app.kubernetes.io/component: database
        app.kubernetes.io/name: db-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
              name: postgres
          envFrom:
            - secretRef:
                name: db-credentials
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "yogawsetiawan34234", "-d", "db-demo"]
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "yogawsetiawan34234", "-d", "db-demo"]
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db-pvc