apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: boutique
  labels:
    app: auth
spec:
  type: ClusterIP
  selector:
    app: auth
  ports:
    - port: 3002
      targetPort: 3002
      protocol: TCP
      name: http
