apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: dev
type: Opaque
stringData:
  AUTH_DATABASE_URL: "postgresql://postgres:postgres123@postgres:5432/auth_db"
  PRODUCT_DATABASE_URL: "postgresql://postgres:postgres123@postgres:5432/products_db"
  ORDER_SERVICE_DATABASE_URL: "postgresql://postgres:postgres123@postgres:5432/orders_db"
  ORDERS_DATABASE_URL: "postgresql://postgres:postgres123@postgres:5432/orders_db"
  USER_DATABASE_URL: "postgresql://postgres:postgres123@postgres:5432/users_db"
