apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: boutique
data:
  NODE_ENV: "production"
  PORT: "3001"
  AUTH_SERVICE_URL: "http://auth:3002"
  PRODUCTS_SERVICE_URL: "http://product:3003"
  ORDER_SERVICE_URL: "http://order-service:3004"
  ORDERS_SERVICE_URL: "http://orders:3005"
  USERS_SERVICE_URL: "http://user:3006"
