apiVersion: v1
kind: Service
metadata:
  name: orders
  namespace: dev
  labels:
    app: orders
spec:
  type: ClusterIP
  selector:
    app: orders
  ports:
    - port: 3005
      targetPort: 3005
      protocol: TCP
      name: http
