apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  namespace: dev
  labels:
    app: product
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: product:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3003
              name: http
          env:
            - name: PORT
              value: "3003"
            - name: ENV_NODE
              value: "production"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: PRODUCT_DATABASE_URL
          readinessProbe:
            httpGet:
              path: /health
              port: 3003
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3003
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
