apiVersion: v1
kind: Service
metadata:
  name: users
  namespace: dev
  labels:
    app: user
spec:
  type: ClusterIP
  selector:
    app: users
  ports:
    - port: 3006
      targetPort: 3006
      protocol: TCP
      name: http
