apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: boutique
  labels:
    app: user
spec:
  type: ClusterIP
  selector:
    app: user
  ports:
    - port: 3006
      targetPort: 3006
      protocol: TCP
      name: http
