name: CI/CD for Microservices

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  IMAGE_TAG: ${{ github.sha }}
  DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}

jobs:
  setup-terraform:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - auth
          - gateway
          - order-service
          - orders
          - product-service
          - user-service
          - frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: | 
            projects/boutique-microservices/backend/services/*
            projects/boutique-microservices/frontend/

  frontend-backend-build:
    runs-on: ubuntu-latest
    needs: setup-terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build & test frontend
        if: matrix.service == 'frontend'
        working-directory: projects/boutique-microservices/frontend
        run: |
          npm install
          npm run build
          npm test --if-present

      # ---------- BACKEND ----------
      - name: Build & test backend
        if: matrix.service != 'frontend'
        working-directory: projects/boutique-microservices/backend/${{ matrix.service }}
        run: |
          npm build
          npm run build --if-present
          npm test --if-present

  docker-build-push:
    runs-on: ubuntu-latest
    needs: frontend-backend-build
    steps:
      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set Docker context
        id: ctx
        run: |
          if [ "${{ matrix.service }}" == "frontend" ]; then
            echo "path=projects/boutique-microservices/frontend" >> $GITHUB_OUTPUT
          else
            echo "path=projects/boutique-microservices/backend/${{ matrix.service }}" >> $GITHUB_OUTPUT
          fi

      - name: Build & push Docker image
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v6
        with:
          context: ${{ steps.ctx.outputs.path }}
          push: true
          tags: |
            ${{ env.DOCKERHUB_USERNAME }}/${{ matrix.service }}:${{ env.IMAGE_TAG }}
            ${{ env.DOCKERHUB_USERNAME }}/${{ matrix.service }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max